---
title: "Acemoglu"
output: html_notebook
---

```{r}
library(tidyverse)
library(grf)
library(rpart)
data <- read_csv('titanic.csv')
```
```{r}
data <- data %>% 
    mutate(Sex1 = recode(Sex, 
                      "male" = 0, 
                      "female" = 1))

data_train <- data %>% select_if(is.numeric)
```


```{r}
set.seed(1993)

# cf1 <- grf::causal_forest(data_train %>% select(-Survived, -Sex1), data$Survived, data$Sex1, num.trees = 1)
# 
# cf2 <- grf::causal_forest(data_train %>% select(-Survived, -Sex1), data$Survived, data$Sex1, num.trees = 1)
# 
# predict(cf1)
# predict(cf2)
# 
# forest_list = list(cf1, cf2)

fit_cf_progressively <- function (X, Y, W, num.trees) {
  # Initialise i
  i <- 0
  
  while (i >= num.trees) {
    # Fit a new tree
    new_tree <- grf::causal_forest(X, Y, W, num.trees = 1)
    
    # Merge with existing forest
    if (i == 1) {
      # Assign tree to forest, don't merge
      new_forest <- new_tree
      
      # Initialise changes vector
      changes <- c()
      
    } else {
      # Merge forests
      old_forest <- new_forest
      new_forest <- merge_forests(list(old_forest, new_tree))
    }
    
    # Compute change
    individual_differences <- predict(old_forest)$predictions - predict(new_forest)$predictions
    
    # Square and average
    changes <- c(changes, mean(individual_differences ** 2))
    
  }
  
  # Increment i
  i <- i + 1
  
  return(list(new_forest, changes))
}

pcf <- fit_cf_progressively(data_train %>% select(-Survived, -Sex1), data$Survived, data$Sex1, num.trees = 2000)

```

```{r}
evaluate_node <- function (fit, node_num, datapoint) {
  node <- fit[[node_num]]
  
  # Check if node is leaf
  if (node$is_leaf) return(node$leaf_stats)
  
  if (!is.na(datapoint[node$split_variable])) {
    evaluation <- datapoint[node$split_variable] <= node$split_value
  } else {
    evaluation <- node$send_missing_left
  }
  
  if (evaluation) {
    evaluate_node(fit, node$left_child, datapoint)
  } else {
    evaluate_node(fit, node$right_child, datapoint)
  }
}

predict_datapoint <- function (fit, datapoint) {
  if (class(fit) != "grf_tree") stop("Input is not a causal tree")
  
  root_node <- fit$nodes[[1]]
  
  evaluate_node()
}

predict_casual_tree <- function (fit, data) {
  data %>%
    mutate(predicted_y = avg_Y,
           predicted_w = avg_W)
}
```

```{r}
evaluate_node(test_tree, 1, data[2,])
```


```{r}
test_tree <- get_tree(cf, 11)

rpart_tree <- rpart(Survived ~ ., data = data %>% select(-Sex1, -Name))
plot(test_tree)

# predict(test_tree, data)
```

